"""hub schema: skill, skill_file, mcp_connection

Initial revision of the hub business-schema chain (version_table:
alembic_version_hub). Autogenerated, then hand-pruned: LangGraph-owned
tables are not in hub metadata, so autogenerate misread them as drops.
DDL uses plain column types — JsonbSafe/EncryptedJson are runtime
TypeDecorators applied by the ORM, not DDL concerns.
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "7639c0070845"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "skill",
        sa.Column("skill_id", sa.Text(), server_default=sa.text("gen_random_uuid()::text"), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("license", sa.Text(), nullable=True),
        sa.Column(
            "metadata", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False
        ),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("skill_id"),
    )
    op.create_index("idx_skill_user", "skill", ["user_id"], unique=False)
    op.create_index("idx_skill_user_name", "skill", ["user_id", "name"], unique=True)

    op.create_table(
        "skill_file",
        sa.Column("skill_file_id", sa.Text(), server_default=sa.text("gen_random_uuid()::text"), nullable=False),
        sa.Column("skill_id", sa.Text(), nullable=False),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("content", sa.LargeBinary(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["skill_id"], ["skill.skill_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("skill_file_id"),
    )
    op.create_index("idx_skill_file_skill", "skill_file", ["skill_id"], unique=False)
    op.create_index("idx_skill_file_skill_path", "skill_file", ["skill_id", "path"], unique=True)

    op.create_table(
        "mcp_connection",
        sa.Column("mcp_connection_id", sa.Text(), server_default=sa.text("gen_random_uuid()::text"), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("transport", sa.Text(), server_default=sa.text("'streamable_http'"), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        # Fernet-encrypted JSON token (EncryptedJson TypeDecorator at the ORM
        # layer) — credentials are never stored as plaintext.
        sa.Column("headers", sa.Text(), nullable=True),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("mcp_connection_id"),
    )
    op.create_index("idx_mcp_connection_user", "mcp_connection", ["user_id"], unique=False)
    op.create_index("idx_mcp_connection_user_name", "mcp_connection", ["user_id", "name"], unique=True)


def downgrade() -> None:
    op.drop_index("idx_mcp_connection_user_name", table_name="mcp_connection")
    op.drop_index("idx_mcp_connection_user", table_name="mcp_connection")
    op.drop_table("mcp_connection")
    op.drop_index("idx_skill_file_skill_path", table_name="skill_file")
    op.drop_index("idx_skill_file_skill", table_name="skill_file")
    op.drop_table("skill_file")
    op.drop_index("idx_skill_user_name", table_name="skill")
    op.drop_index("idx_skill_user", table_name="skill")
    op.drop_table("skill")
