"""Audit ledger table (append-only).

Revision ID: 7c1f9a4e2d10
Revises: 51dcc8f487fb
Create Date: 2026-10-10 15:40:00.000000

Hand-written rather than autogenerated: the table has no relationships to
existing schema, and a migration that can be reviewed as DDL is worth more here
than one produced by comparing against a live database.
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text

import agent_server.repo.orm

# revision identifiers, used by Alembic.
revision = "7c1f9a4e2d10"
down_revision = "51dcc8f487fb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "audit_log",
        sa.Column("entry_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Text(), nullable=True),
        sa.Column("thread_id", sa.Text(), nullable=True),
        sa.Column("run_id", sa.Text(), nullable=True),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("resource", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("detail", agent_server.repo.orm.JsonbSafe(astext_type=Text()), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("entry_id"),
    )
    op.create_index("idx_audit_log_user_created", "audit_log", ["user_id", "created_at"], unique=False)
    op.create_index("idx_audit_log_thread", "audit_log", ["thread_id"], unique=False)
    op.create_index("idx_audit_log_run", "audit_log", ["run_id"], unique=False)
    op.create_index("idx_audit_log_action_created", "audit_log", ["action", "created_at"], unique=False)


def downgrade() -> None:
    op.drop_index("idx_audit_log_action_created", table_name="audit_log")
    op.drop_index("idx_audit_log_run", table_name="audit_log")
    op.drop_index("idx_audit_log_thread", table_name="audit_log")
    op.drop_index("idx_audit_log_user_created", table_name="audit_log")
    op.drop_table("audit_log")
